# syntax=docker/dockerfile:1
FROM golang:1.19-alpine

# Set the current working directory inside the container 
WORKDIR /app

# Install go watch to run gin server in watch mod
RUN go install github.com/mitranim/gow@latest

# Copy go mod and sum files 
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed 
RUN go mod download 

# Copy the source from the current directory to the working Directory inside the container 
COPY . .

# Expose port 5000 to the outside world
EXPOSE 5000

#Command to run the executable
CMD ["gow", "run", "main.go"]